"""empty message

Revision ID: d5018ec6cbbc
Revises: 
Create Date: 2023-04-11 19:47:04.614287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5018ec6cbbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('surname', sa.String(length=32), nullable=False),
    sa.Column('patronymic', sa.String(length=32), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=True),
    sa.Column('type_user', sa.Enum('USER', 'CHECKER', 'ADMIN', name='typeuser'), nullable=True),
    sa.Column('last_activ', sa.DateTime(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
